import './globals.css';
import type { Metadata } from 'next';
import Navbar from '../components/custom/Navbar';

export const metadata: Metadata = {
  title: 'My App',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className=' bg-app-black'>
        <Navbar />
        <main className="p-4">{children}</main>
      </body>
    </html>
  );
}