import './globals.css'
import type { Metadata } from 'next'
import Navbar from '../components/custom/Navbar'
import Footer from '../components/custom/Footer'

export const metadata: Metadata = {
  title: 'My App',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className=" bg-app-black min-h-screen flex flex-col">
        <Navbar />

        {/* Main content expands to fill space, but no padding around footer */}
        <main className="flex-grow flex flex-col items-center justify-center px-4">
          {children}
        </main>

        {/* Footer is outside the main area */}
        <Footer />
      </body>
    </html>
  )
}
